export const foodItems = [
  // ...same items as before, but with updated and diversified categories as shown below...
  {
    id: 1,
    name: "Masala Dosa",
    description: "Crispy rice & lentil crepe stuffed with spicy potato filling, served with sambar and coconut chutney.",
    price: 60,
    image: "https://anjappar.ch/wp-content/uploads/2023/11/Masala-Dosa-New.jpg",
    category: "Breakfast",
  },
  {
    id: 2,
    name: "Idli",
    description: "Soft steamed rice cakes, served with coconut chutney and sambar.",
    price: 30,
    image: "https://holycowvegan.net/wp-content/uploads/2019/04/idli-recipe-32.jpg",
    category: "Breakfast",
  },
  {
    id: 3,
    name: "Medu Vada",
    description: "Crispy fried lentil doughnuts, served with coconut chutney and sambar.",
    price: 35,
    image: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/07/vada-recipe-1.jpg",
    category: "Breakfast",
  },
  {
    id: 4,
    name: "Onion Uttapam",
    description: "Thick rice pancake topped with onions, tomatoes, and chilies, served with chutney.",
    price: 45,
    image: "https://foodoncall.co.in/wp-content/uploads/2017/10/onion-uttapam.jpg",
    category: "Breakfast",
  },
  {
    id: 5,
    name: "Pongal",
    description: "Creamy rice and lentil porridge tempered with black pepper, cumin, and ghee.",
    price: 40,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/01/pongal-ven-pongal.jpg",
    category: "Breakfast",
  },
  {
    id: 6,
    name: "Lemon Rice",
    description: "Aromatic rice flavored with lemon juice, curry leaves, and mustard seeds.",
    price: 38,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/lemon-rice-recipe.jpg",
    category: "Lunch",
  },
  {
    id: 7,
    name: "Sambar Rice",
    description: "Steamed rice mixed with tangy and spicy lentil sambar and vegetables.",
    price: 42,
    image: "https://www.kannammacooks.com/wp-content/uploads/sambar-sadam-made-with-brown-rice-recipe-1-3.jpg",
    category: "Lunch",
  },
  {
    id: 8,
    name: "Curd Rice",
    description: "Cooling rice mixed with yogurt and mild spices, topped with pomegranate and curry leaves.",
    price: 33,
    image: "https://www.vegrecipesofindia.com/wp-content/uploads/2016/07/curd-rice-2-500x500.jpg",
    category: "Lunch",
  },
  {
    id: 9,
    name: "Rasam",
    description: "A spicy and tangy tomato-based soup, flavored with tamarind, pepper, and garlic.",
    price: 28,
    image: "https://rakskitchen.net/wp-content/uploads/2013/09/9728762322_375faf2d93_z-500x500.jpg",
    category: "Lunch",
  },
  {
    id: 10,
    name: "Kesari Bath",
    description: "Sweet semolina pudding flavored with saffron, cardamom, and garnished with cashews.",
    price: 32,
    image: "https://upload.wikimedia.org/wikipedia/commons/9/92/KEsari_baat.jpg",
    category: "Snacks",
  },
  {
    id: 11,
    name: "Rava Idli",
    description: "Steamed semolina cakes with mustard seeds, curry leaves, and yogurt.",
    price: 36,
    image: "https://www.vegrecipesofindia.com/wp-content/uploads/2013/11/rava-idli-3-500x500.jpg",
    category: "Breakfast",
  },
  {
    id: 12,
    name: "Upma",
    description: "Savory semolina porridge with vegetables and tempered spices.",
    price: 34,
    image: "https://rakskitchen.net/wp-content/uploads/2013/02/upma-recipe-feat.jpg",
    category: "Breakfast",
  },
  {
    id: 13,
    name: "Vegetable Kurma",
    description: "Rich coconut-based curry with mixed vegetables and mild spices.",
    price: 50,
    image: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/01/veg-kurma-korma-recipe-500x500.jpg",
    category: "Lunch",
  },
  {
    id: 14,
    name: "Chapati with Kurma",
    description: "Whole wheat flatbread served with a flavorful vegetable kurma.",
    price: 44,
    image: "https://udupi-recipes.com/wp-content/uploads/2016/06/Easy-Peas-kurma.jpg",
    category: "Dinner",
  },
  {
    id: 15,
    name: "Plain Dosa",
    description: "Classic thin crispy dosa served with coconut chutney and sambar.",
    price: 32,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/dosa-recipe.jpg",
    category: "Breakfast",
  },
  {
    id: 16,
    name: "Ghee Roast Dosa",
    description: "Crispy dosa roasted in ghee, served with chutney and sambar.",
    price: 48,
    image: "https://www.squarecut.net/wp-content/uploads/2024/08/crispy-crepes-made-barnyard-millets-lentils-commonly-known-as-milled-ghee-roast-dosa-plated-conical-shape-rolls-served-238893976.webp",
    category: "Dinner",
  },
  {
    id: 17,
    name: "Mysore Masala Dosa",
    description: "Dosa spread with spicy red chutney and potato filling.",
    price: 52,
    image: "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg",
    category: "Dinner",
  },
  {
    id: 18,
    name: "Set Dosa",
    description: "Soft, spongy, small dosas served in a set of three with sagu and chutney.",
    price: 38,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2014/12/set-dosa-recipe-1.jpg",
    category: "Breakfast",
  },
  {
    id: 19,
    name: "Ragi Dosa",
    description: "Healthy finger millet dosa, served with coconut chutney.",
    price: 40,
    image: "https://www.solara.in/cdn/shop/articles/ragi_dosa.jpg?v=1712127176&width=2048",
    category: "Healthy",
  },
  {
    id: 20,
    name: "Neer Dosa",
    description: "Soft, lacy rice dosa from Karnataka, served with coconut chutney.",
    price: 42,
    image: "https://static.toiimg.com/thumb/53541904.cms?imgsize=168967&width=800&height=800",
    category: "Breakfast",
  },
  {
    id: 21,
    name: "Appam",
    description: "Soft, fluffy rice pancakes with crispy edges, served with vegetable stew.",
    price: 45,
    image: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/pooja/Instant_Rava_appam_with_vegetables.jpg",
    category: "Breakfast",
  },
  {
    id: 22,
    name: "Pesarattu",
    description: "Green gram dosa from Andhra Pradesh, served with ginger chutney.",
    price: 39,
    image: "https://cdn3.foodviva.com/static-content/food-images/andhra-recipes/pesarattu/pesarattu.jpg",
    category: "Healthy",
  },
  {
    id: 23,
    name: "Bisi Bele Bath",
    description: "Hot lentil rice with vegetables, spices, and a dollop of ghee.",
    price: 50,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/07/bisi-bele-bath-recipe.jpg",
    category: "Lunch",
  },
  {
    id: 24,
    name: "Avial",
    description: "Kerala-style mixed vegetable curry with coconut and yogurt.",
    price: 50,
    image: "https://foodtrails25.com/wp-content/uploads/2023/08/Avial-Aiyal.jpg",
    category: "Lunch",
  },
  {
    id: 25,
    name: "Kootu",
    description: "Mild Tamil-style dal curry with vegetables and coconut.",
    price: 43,
    image: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Cabbage_kootu.jpg",
    category: "Healthy",
  },
  {
    id: 26,
    name: "Thayir Sadam",
    description: "Classic Tamil curd rice with tempering and pomegranate.",
    price: 35,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/curd-rice-thayir-sadam.jpg",
    category: "Lunch",
  },
  {
    id: 27,
    name: "Coconut Chutney",
    description: "Fresh coconut chutney with green chilies and tempered spices.",
    price: 15,
    image: "https://shwetainthekitchen.com/wp-content/uploads/2022/04/Coconut-Chutney.jpg",
    category: "Snacks",
  },
  {
    id: 28,
    name: "Tomato Chutney",
    description: "Tangy tomato chutney with garlic, red chilies, and curry leaves.",
    price: 15,
    image: "https://i0.wp.com/kalimirchbysmita.com/wp-content/uploads/2015/07/Tomato-Chutney04.jpg",
    category: "Snacks",
  },
  {
    id: 29,
    name: "Gunpowder (Idli Podi)",
    description: "Spicy lentil powder served with sesame oil and idlis.",
    price: 12,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/04/idli-podi-recipe.webp",
    category: "Snacks",
  },
  {
    id: 30,
    name: "Mixed Vegetable Sagu",
    description: "Mildly spiced Karnataka-style mixed vegetable curry.",
    price: 35,
    image: "https://www.indianveggiedelight.com/wp-content/uploads/2024/01/vegetable-sagu-featured.jpg",
    category: "Dinner",
  },
  {
    id: 31,
    name: "Sambar Vada",
    description: "Crispy vadas soaked in hot sambar, topped with onions and coriander.",
    price: 38,
    image: "https://vegecravings.com/wp-content/uploads/2018/02/Medu-Vada-Recipe-Step-By-Step-Instructions-500x500.jpg",
    category: "Snacks",
  },
  {
    id: 32,
    name: "Kara Kuzhambu",
    description: "A tangy and spicy tamarind-based curry with vegetables.",
    price: 45,
    image: "https://i.ytimg.com/vi/5q6HLbSt93c/maxresdefault.jpg",
    category: "Lunch",
  },
  {
    id: 33,
    name: "Chettinad Chicken Curry",
    description: "Fiery Chettinad-style chicken curry with aromatic spices.",
    price: 70,
    image: "https://www.whiskaffair.com/wp-content/uploads/2020/09/Chicken-Chettinad-Curry-2-3.jpg",
    category: "Dinner",
  },
  {
    id: 34,
    name: "Malabar Parotta",
    description: "Flaky layered flatbread from Kerala, best with curries.",
    price: 40,
    image: "https://www.tastycircle.com/wp-content/uploads/2014/06/kerala-parotta.jpg",
    category: "Dinner",
  },
  {
    id: 35,
    name: "Kadalai Curry",
    description: "Black chickpea curry in a coconut-based gravy.",
    price: 45,
    image: "https://cakeworkorange.com/wp-content/uploads/2021/01/kerala-kadala-curry-instant-pot.jpg",
    category: "Lunch",
  },
  {
    id: 36,
    name: "Puttu Kadala",
    description: "Steamed rice flour cylinders with kadala curry.",
    price: 48,
    image: "https://www.sailusfood.com/wp-content/uploads/2012/12/puttu-kadala-kerala-vegetarian-recipes.jpg",
    category: "Breakfast",
  },
  {
    id: 37,
    name: "Mangalore Buns",
    description: "Sweet, soft banana puris from Mangalore.",
    price: 32,
    image: "https://www.ruchikrandhap.com/wp-content/uploads/2010/03/IMG_5080-scaled.jpg",
    category: "Snacks",
  },
  {
    id: 38,
    name: "Vazhakka Bajji",
    description: "Deep-fried raw banana fritters with gram flour batter.",
    price: 28,
    image: "https://i.ytimg.com/vi/SMCdfBxRAi4/maxresdefault.jpg",
    category: "Snacks",
  },
  {
    id: 39,
    name: "Murukku",
    description: "Crunchy deep-fried snack made of rice and urad dal flour.",
    price: 20,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/10/murukku-recipe.jpg",
    category: "Snacks",
  },
  {
    id: 40,
    name: "Banana Chips",
    description: "Thin, crispy fried banana slices lightly salted.",
    price: 18,
    image: "https://chandravilas.com/wp-content/uploads/2022/09/Banana-Chips-yellow-top1.jpg",
    category: "Snacks",
  },
  {
    id: 41,
    name: "Sundal",
    description: "Steamed chickpeas tossed with coconut and spices.",
    price: 25,
    image: "https://butfirstchai.com/wp-content/uploads/2021/04/chickpea-sundal-recipe.jpg",
    category: "Snacks",
  },
  {
    id: 42,
    name: "Puliyodarai",
    description: "Tangy tamarind rice with peanuts and curry leaves.",
    price: 35,
    image: "https://tastyappetite.net/static/d308d466a36df76bdde963d7a61e6c86/14b42/27b5aea1f08cafe24116f0d70f07306c.jpg",
    category: "Lunch",
  },
  {
    id: 43,
    name: "Kara Sev",
    description: "Spicy, crunchy noodle-like snack made with besan.",
    price: 20,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2019/04/karasev-diwali-snacks.jpg",
    category: "Snacks",
  },
  {
    id: 44,
    name: "Ela Ada",
    description: "Steamed rice flour pockets with coconut-jaggery filling.",
    price: 28,
    image: "https://static.toiimg.com/thumb/60031358.cms?imgsize=416936&width=800&height=800",
    category: "Snacks",
  },
  {
    id: 45,
    name: "Olan",
    description: "Mild Kerala stew with ash gourd, coconut milk, and beans.",
    price: 38,
    image: "https://www.sharmispassions.com/wp-content/uploads/2013/09/olan7.jpg",
    category: "Lunch",
  },
  {
    id: 46,
    name: "Payasam",
    description: "Sweet pudding made from rice, milk, and cardamom.",
    price: 30,
    image: "https://www.sharmispassions.com/wp-content/uploads/2023/10/semiya-payasam1.jpg",
    category: "Snacks",
  },
  {
    id: 47,
    name: "Vattayappam",
    description: "Soft, steamed rice cakes from Kerala.",
    price: 30,
    image: "https://static.toiimg.com/thumb/59399239.cms?imgsize=1071908&width=800&height=800",
    category: "Snacks",
  },
  {
    id: 48,
    name: "Ulli Theeyal",
    description: "Shallots cooked in a roasted coconut and tamarind gravy.",
    price: 35,
    image: "https://www.masalakorb.com/wp-content/uploads/2023/08/Ulli-Theeyal-Recipe-Kerala-Style-V1.jpg",
    category: "Lunch",
  },
  {
    id: 49,
    name: "Kappa Meen Curry",
    description: "Boiled tapioca served with spicy fish curry.",
    price: 60,
    image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgnmhClrwFa9uSzt4xZturIsV4YxTzFJPlMP7uzgweM1vcDiCWJRYqSrx3TpbcnaFO_IeZJH6Nbkad-fWyJeo-l-pKUbROUTyqQ9idk9tqiDo4qH83CciTw1RhXGw0ytJxKDTRy4fXfxgw/s1600/kappa+meen+curry.JPG",
    category: "Lunch",
  },
  {
    id: 50,
    name: "Thattai",
    description: "Crispy, flat rice crackers seasoned with spices.",
    price: 22,
    image: "https://www.vegrecipesofindia.com/wp-content/uploads/2019/09/thattai-recipe.jpg",
    category: "Snacks",
  },
  {
    id: 51,
    name: "Parippu Vada",
    description: "Crunchy chana dal fritters, perfect tea-time snack.",
    price: 18,
    image: "https://somethingiscooking.com/wp-content/uploads/2019/04/parippu-vada-2.jpg",
    category: "Snacks",
  },
  {
    id: 52,
    name: "Chicken 65",
    description: "Spicy, deep-fried South Indian chicken bites.",
    price: 65,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/chicken-65-swasthi.webp",
    category: "Snacks",
  },
  {
    id: 53,
    name: "Andhra Chicken Fry",
    description: "Hot and spicy Andhra-style fried chicken.",
    price: 68,
    image: "https://theyummydelights.com/wp-content/uploads/2022/05/andhra-chicken-fry.jpg",
    category: "Dinner",
  },
  {
    id: 54,
    name: "Karaikudi Mutton",
    description: "Traditional Chettinad mutton curry with robust spices.",
    price: 85,
    image: "https://www.yummytummyaarthi.com/wp-content/uploads/2021/11/lamb-chettinad-1.jpeg",
    category: "Dinner",
  },
  {
    id: 55,
    name: "Chettinad Fish Fry",
    description: "Crispy fried fish marinated in Chettinad spices.",
    price: 70,
    image: "https://www.cookingandme.com/wp-content/uploads/2016/12/chettinad-fish-fry-meen-varuval-recipe-ed-500x500.jpg",
    category: "Dinner",
  },
  {
    id: 56,
    name: "Ambur Biryani",
    description: "Famous Tamil Nadu biryani with seeraga samba rice.",
    price: 75,
    image: "https://theartisticcook.com/wp-content/uploads/2023/10/amburbir.jpg",
    category: "Dinner",
  },
  {
    id: 57,
    name: "Hyderabadi Biryani",
    description: "Iconic layered rice and meat biryani from Hyderabad.",
    price: 80,
    image: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Hyderabadi_Chicken_Biryani.jpg",
    category: "Dinner",
  },
  {
    id: 58,
    name: "Filter Coffee",
    description: "Strong, aromatic South Indian filter coffee with froth.",
    price: 15,
    image: "https://truesouth.in/cdn/shop/files/southindian1.jpg?v=1707477021",
    category: "Drinks",
  },
  {
    id: 59,
    name: "Rava Upma",
    description: "Semolina cooked with veggies and tempered spices.",
    price: 32,
    image: "https://rakskitchen.net/wp-content/uploads/2013/02/upma-recipe-feat.jpg",
    category: "Breakfast",
  },
  {
    id: 60,
    name: "Kharabath",
    description: "Spicy, soft upma from Karnataka with vegetables.",
    price: 37,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/07/khara-bath-recipe.jpg",
    category: "Breakfast",
  },
  {
    id: 61,
    name: "Chow Chow Bath",
    description: "Combo of kharabath and kesari bath served together.",
    price: 40,
    image: "https://karnatakatourism.org/wp-content/uploads/2023/03/Chow-Chow-Bath-thumbnail-400x300-1.jpg",
    category: "Breakfast",
  },
  {
    id: 62,
    name: "Obbattu (Holige)",
    description: "Sweet flatbread stuffed with lentil and jaggery.",
    price: 38,
    image: "https://karnatakatourism.org/wp-content/uploads/2020/05/57_2020_Obbatu_-1.jpg",
    category: "Snacks",
  },
  {
    id: 63,
    name: "Pineapple Gojju",
    description: "Tangy, sweet pineapple curry with coconut and spices.",
    price: 30,
    image: "https://www.kamalascorner.com/wp-content/uploads/2009/06/pineapple-gojju.jpg",
    category: "Lunch",
  },
  {
    id: 64,
    name: "Bonda Soup",
    description: "Karnataka special Bonda Soup | Urad dal Fritters in Spicy Dal Soup",
    price: 35,
    image: "https://vismaifood.com/storage/app/uploads/public/140/13f/a99/thumb__700_0_0_0_auto.jpg",
    category: "Snacks",
  },
  {
    id: 65,
    name: "Nethili Fry",
    description: "Crispy fried anchovies coated in spicy masala.",
    price: 55,
    image: "https://anjappar.ch/wp-content/uploads/2023/11/Nethili-fish-fry.jpg",
    category: "Dinner",
  },
  {
    id: 66,
    name: "Kothu Parotta",
    description: "Shredded parotta stir-fried with egg, spices, and veggies.",
    price: 48,
    image: "https://www.relishthebite.com/wp-content/uploads/2015/05/Kothuparotta8.jpg",
    category: "Dinner",
  },
  {
    id: 67,
    name: "Thalassery Biryani",
    description: "Fragrant Kerala biryani with Malabar spices.",
    price: 82,
    image: "https://images.slurrp.com/prod/recipe_images/transcribe/main%20course/Thalassery-Biryani.webp",
    category: "Dinner",
  },
  {
    id: 68,
    name: "Pesarapappu",
    description: "Simple Andhra moong dal curry.",
    price: 25,
    image: "https://ruralkingz.com/wp-content/uploads/2020/09/pesara-pappu.jpg",
    category: "Healthy",
  },
  {
    id: 69,
    name: "Chicken Chettinad",
    description: "Spicy Chettinad chicken curry with coconut and pepper.",
    price: 70,
    image: "https://www.cookwithnabeela.com/wp-content/uploads/2024/03/ChickenChettinad.webp",
    category: "Dinner",
  },
  {
    id: 70,
    name: "Cabbage Thoran",
    description: "Kerala-style stir-fried cabbage with coconut.",
    price: 28,
    image: "https://www.sharmispassions.com/wp-content/uploads/2021/08/cabbage-thoran5-1.jpg",
    category: "Healthy",
  },
  {
    id: 71,
    name: "Beetroot Pachadi",
    description: "Beetroot and yogurt raita with coconut and mustard.",
    price: 20,
    image: "https://vanitascorner.com/wp-content/uploads/2023/05/beetroot-pachadi-FB.jpg",
    category: "Healthy",
  },
  {
    id: 72,
    name: "Drumstick Sambar",
    description: "Sambar made with drumsticks and assorted vegetables.",
    price: 40,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2024/06/drumstick-sambar-recipe.jpg",
    category: "Lunch",
  },
  {
    id: 73,
    name: "Beans Poriyal",
    description: "Dry stir-fried green beans with coconut and mustard.",
    price: 30,
    image: "https://www.tomatoblues.com/wp-content/uploads/2022/08/beans-poriyal-2-500x500.jpg",
    category: "Healthy",
  },
  {
    id: 74,
    name: "Capsicum Masala",
    description: "Bell peppers cooked in a spicy coconut masala.",
    price: 36,
    image: "https://cdn2.foodviva.com/static-content/food-images/curry-recipes/capsicum-masala-curry/capsicum-masala-curry.jpg",
    category: "Lunch",
  },
  {
    id: 75,
    name: "Tomato Pappu",
    description: "Andhra-style tangy tomato dal with toor dal.",
    price: 28,
    image: "https://www.maggi.in/sites/default/files/srh_recipes/c6c15056f5bc4b8d7835709d72665fe5.jpg",
    category: "Lunch",
  },
  {
    id: 76,
    name: "Bagara Rice",
    description: "Aromatic rice cooked with whole spices and herbs.",
    price: 38,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2024/06/bagara-rice-bagara-chawal.jpg",
    category: "Lunch",
  },
  {
    id: 77,
    name: "Egg Kurma",
    description: "Boiled eggs in a creamy coconut-based kurma.",
    price: 50,
    image: "https://myfoodstory.com/wp-content/uploads/2015/11/south-indian-style-egg-curry-recipe.1024x1024-3.jpg",
    category: "Dinner",
  },
  {
    id: 78,
    name: "Paya Soup",
    description: "Spiced mutton trotters soup from South India.",
    price: 55,
    image: "https://jamilghar.com/wp-content/uploads/2022/10/mutton_paya_soup7-scaled.jpeg",
    category: "Dinner",
  },
  {
    id: 79,
    name: "Ragi Mudde",
    description: "Steamed finger millet balls, Karnataka staple.",
    price: 30,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/02/ragi-mudde-recipe-500x500.jpg",
    category: "Healthy",
  },
  {
    id: 80,
    name: "Uppittu",
    description: "Karnataka-style upma with veggies and spices.",
    price: 33,
    image: "https://static.toiimg.com/thumb/86386635.cms?imgsize=50106&width=800&height=800",
    category: "Breakfast",
  },
  {
    id: 81,
    name: "Vangi Bath",
    description: "Brinjal rice flavored with vangi bath masala.",
    price: 38,
    image: "https://www.indianveggiedelight.com/wp-content/uploads/2024/01/vangibhath-featured-500x500.jpg",
    category: "Lunch",
  },
  {
    id: 82,
    name: "Mysore Pak",
    description: "Classic South Indian sweet made with gram flour and ghee.",
    price: 42,
    image: "https://static.toiimg.com/photo/53376135.cms",
    category: "Snacks",
  },
  {
    id: 83,
    name: "Badam Halwa",
    description: "Rich almond dessert cooked with ghee and sugar.",
    price: 45,
    image: "https://kiipfit.com/wp-content/uploads/2024/09/badam-halwa-4.jpg",
    category: "Snacks",
  },
  {
    id: 84,
    name: "Sakkarai Pongal",
    description: "Sweet rice and jaggery pudding with ghee and cashews.",
    price: 38,
    image: "https://www.sharmispassions.com/wp-content/uploads/2013/05/SweetPongal1-e1673485715747-500x500.jpg",
    category: "Snacks",
  },
  {
    id: 85,
    name: "Moong Dal Payasam",
    description: "Moong dal and coconut milk sweet pudding.",
    price: 34,
    image: "https://myheartbeets.com/wp-content/uploads/2019/02/moong-dal-payasam-500x500.jpg",
    category: "Snacks",
  },
  {
    id: 86,
    name: "Pineapple Kesari",
    description: "Semolina dessert flavored with pineapple and saffron.",
    price: 30,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/07/pineapple-kesari-pineapple-sheera-recipe.jpg",
    category: "Snacks",
  },
  {
    id: 87,
    name: "Jangri",
    description: "Deep-fried spirals of urad dal soaked in sugar syrup.",
    price: 22,
    image: "https://vellankifoods.com/cdn/shop/products/jangri_ghee.jpg?v=1680180402",
    category: "Snacks",
  },
  {
    id: 88,
    name: "Adirasam",
    description: "Sweet rice flour doughnuts flavored with jaggery.",
    price: 18,
    image: "https://rakskitchen.net/wp-content/uploads/2012/10/adhirasam-feat.jpg",
    category: "Snacks",
  },
  {
    id: 89,
    name: "Rava Kesari",
    description: "Semolina dessert with ghee, sugar, and cardamom.",
    price: 20,
    image: "https://cookingfromheart.com/wp-content/uploads/2017/08/Rava-Kesari-6.jpg",
    category: "Snacks",
  },
  {
    id: 90,
    name: "Kaju Katli",
    description: "Diamond-shaped cashew fudge, festival favorite.",
    price: 32,
    image: "https://www.nestleprofessional.in/sites/default/files/2022-07/Kaju-Katli.jpg",
    category: "Snacks",
  },
  {
    id: 91,
    name: "Kozhukattai",
    description: "Steamed rice flour dumplings with sweet coconut filling.",
    price: 28,
    image: "https://desertfoodfeed.com/wp-content/uploads/2021/03/Kozhukattai-Kozhukatta-Recipe.jpg",
    category: "Snacks",
  },
  {
    id: 92,
    name: "Sweet Poli",
    description: "Flatbread stuffed with sweet lentil filling.",
    price: 24,
    image: "https://www.kamalascorner.com/wp-content/uploads/2010/09/sweet-dhal-poli.jpg",
    category: "Snacks",
  },
  {
    id: 93,
    name: "Idiyappam",
    description: "String hoppers made from rice flour, served with coconut milk.",
    price: 26,
    image: "https://www.awesomecuisine.com/wp-content/uploads/2008/02/idiyappam.jpg",
    category: "Breakfast",
  },
  {
    id: 94,
    name: "Chettinad Prawn Curry",
    description: "Spicy Chettinad-style prawn curry with coconut.",
    price: 78,
    image: "https://www.funfoodfrolic.com/wp-content/uploads/2020/12/Chettinad-Prawn-Masala-Thumbnail.jpg",
    category: "Dinner",
  },
  {
    id: 95,
    name: "Fish Molee",
    description: "Kerala fish stew with coconut milk and light spices.",
    price: 80,
    image: "https://www.pepperdelight.com/wp-content/uploads/2018/03/pepper-delight-fish-molly-1.jpg",
    category: "Dinner",
  },
  {
    id: 96,
    name: "Prawn Sukka",
    description: "Dry prawn fry with grated coconut and spices.",
    price: 72,
    image: "https://vanitascorner.com/wp-content/uploads/2021/05/Prawns-Sukka.jpg",
    category: "Dinner",
  },
  {
    id: 97,
    name: "Kallappam",
    description: "Soft Kerala pancakes made with toddy or yeast.",
    price: 30,
    image: "https://www.linuskitchen.com/wp-content/uploads/2013/05/Kallappam-3.jpg",
    category: "Breakfast",
  },
  {
    id: 98,
    name: "Paneer Chettinad",
    description: "Paneer cubes in spicy Chettinad masala.",
    price: 48,
    image: "https://img-global.cpcdn.com/recipes/eb44e9b30a029f9d/1200x630cq70/photo.jpg",
    category: "Dinner",
  },
  {
    id: 99,
    name: "Veg Chettinad Biryani",
    description: "Flavored rice biryani with Chettinad spices and vegetables.",
    price: 55,
    image: "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/sandhya-archanaskitchen.com/Chettinad_Vegetable_Biryani_Recipe.jpg",
    category: "Dinner",
  },
  {
    id: 100,
    name: "Mushroom Pepper Fry",
    description: "Spicy stir-fried mushrooms with black pepper.",
    price: 44,
    image: "https://www.vegrecipesofindia.com/wp-content/uploads/2016/08/mushroom-pepper-fry-recipe-1.jpg",
    category: "Dinner",
  },
 
  {
    id: 101,
    name: "Lassi",
    description: "Chilled yogurt-based drink, sweet or salty, flavored with cardamom.",
    price: 25,
    image: "https://themagicsaucepan.com/wp-content/uploads/2018/05/20180511-salt-lassi-0061-500x500.jpg",
    category: "Drinks",
  },
  {
    id: 102,
    name: "Butter Milk",
    description: "Refreshing spiced buttermilk with curry leaves and ginger.",
    price: 18,
    image: "https://peppybowl.in/wp-content/uploads/2021/09/chaach1-fb_092218053144.jpeg",
    category: "Drinks",
  },
  {
    id: 103,
    name: "Tender Coconut Water",
    description: "Naturally sweet, hydrating coconut water.",
    price: 30,
    image: "https://www.doodhvalefarms.com/_next/image?url=https%3A%2F%2Fd1zh47ill7uy4g.cloudfront.net%2Fproducts%2Fh9I__CJYlz3idyLtFFiiUjN1ZWz5MPhu.png&w=640&q=75",
    category: "Drinks, Healthy",
  },
  {
    id: 104,
    name: "Rose Milk",
    description: "Chilled milk flavored with rose syrup.",
    price: 28,
    image: "https://www.vegrecipesofindia.com/wp-content/uploads/2015/03/rose-milk-recipe-1.jpg",
    category: "Drinks",
  },
  {
    id: 105,
    name: "Badam Milk",
    description: "Sweet almond-flavored milk with cardamom.",
    price: 35,
    image: "https://www.cookwithmanali.com/wp-content/uploads/2014/06/Badam-Milk.jpg",
    category: "Drinks",
  },
  {
    id: 106,
    name: "Filter Coffee (Cold)",
    description: "Chilled version of traditional South Indian filter coffee.",
    price: 22,
    image: "https://konacoffee.nyc/cdn/shop/articles/IMG_2171-2.jpg?v=1719955757&width=300",
    category: "Drinks",
  },
  {
    id: 107,
    name: "Lemon Mint Cooler",
    description: "Fresh lime juice with mint leaves, chilled and lightly sweet.",
    price: 24,
    image: "https://thetoastykitchen.com/wp-content/uploads/2024/06/lemon-mint-cooler-glass.jpg",
    category: "Drinks",
  },
  {
    id: 108,
    name: "Ragi Malt",
    description: "Nutritious finger millet drink, lightly sweetened.",
    price: 30,
    image: "https://vaya.in/recipes/wp-content/uploads/2019/12/Ragi-Malt.jpg",
    category: "Drinks",
  },
  {
    id: 109,
    name: "Carrot Juice",
    description: "Freshly squeezed carrot juice, full of vitamins.",
    price: 27,
    image: "https://vaya.in/recipes/wp-content/uploads/2018/05/Carrot-Juice.jpg",
    category: "Drinks, Healthy",
  },
  {
    id: 110,
    name: "Pineapple Juice",
    description: "Fresh pineapple juice, sweet and tangy.",
    price: 28,
    image: "https://5.imimg.com/data5/LT/XB/MY-28787720/pineapple-drink-500x500.jpg",
    category: "Drinks",
  },
  {
    id: 111,
    name: "Mosambi Juice",
    description: "Sweet lime juice, natural and refreshing.",
    price: 26,
    image: "https://cdn.prod.website-files.com/65056ba428fdd5501ff0ef16/66a74bade12ce6bc65ba821f_666b1f7291c67bae376099e2_AdobeStock_442313901-_1_.webp",
    category: "Drinks",
  },
  {
    id: 112,
    name: "Watermelon Juice",
    description: "Chilled watermelon juice, hydrating and sweet.",
    price: 22,
    image: "https://cdn.loveandlemons.com/wp-content/uploads/2021/06/watermelon-juice.jpg",
    category: "Drinks, Healthy",
  },
  {
    id: 113,
    name: "Cucumber Cooler",
    description: "Cooling cucumber drink with a touch of lemon.",
    price: 20,
    image: "https://www.mygingergarlickitchen.com/wp-content/uploads/2022/06/cucumber-cooler-5.jpg",
    category: "Healthy",
  },
  {
    id: 114,
    name: "Amla Juice",
    description: "Vitamin C-rich Indian gooseberry juice.",
    price: 26,
    image: "https://redcliffelabs.com/myhealth/_next/image/?url=https%3A%2F%2Fmyhealth-redcliffelabs.redcliffelabs.com%2Fmedia%2Fblogcard-images%2FNone%2Ff060e606-238a-4caa-a8eb-f950bdea1158.webp&w=1920&q=75",
    category: "Drinks",
  },
  {
    id: 115,
    name: "Papaya Juice",
    description: "Fresh papaya juice, smooth and sweet.",
    price: 25,
    image: "https://theallnaturalvegan.com/wp-content/uploads/2023/08/papaya-juice-featured-image.jpg",
    category: "Drinks, Healthy",
  },
  {
    id: 116,
    name: "Orange Juice",
    description: "Freshly squeezed orange juice.",
    price: 28,
    image: "https://media.post.rvohealth.io/wp-content/uploads/2020/08/orange-juice-732x549-thumbnail-732x549.jpg",
    category: "Drinks, Healthy",
  },
  {
    id: 117,
    name: "Ginger Lemonade",
    description: "Lemon juice with ginger and honey.",
    price: 22,
    image: "https://www.grocery.coop/sites/default/files/styles/recipe_photo/public/NCG_Dennis_Becker_Honey_Ginger_Lemonade_715x477.jpg?itok=JZ7J-tGZ",
    category: "Drinks, Healthy",
  },
  {
    id: 118,
    name: "Mint Chaas",
    description: "Buttermilk blended with fresh mint leaves.",
    price: 18,
    image: "https://www.relishthebite.com/wp-content/uploads/2014/11/Pudinachaas-6.jpg",
    category: "Drinks, Healthy",
  },
  {
    id: 119,
    name: "Apple Juice",
    description: "Fresh apple juice, naturally sweet.",
    price: 29,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/apple-juice-recipe.jpg",
    category: "Healthy",
  },
  {
    id: 120,
    name: "Sattu Drink",
    description: "Nutritious roasted gram flour drink, cooling and filling.",
    price: 26,
    image: "https://scdn.aro.ie/Sites/50/anandaspa/uploads/images/PanelImages/General/Sattu_Drink__Resized_.jpg",
    category: "Healthy",
  },
  {
    id: 121,
    name: "Herbal Tea",
    description: "Hot or iced herbal tea with spices.",
    price: 22,
    image: "https://cdn.shopify.com/s/files/1/0623/9010/8391/files/Herbal_Tea_898_1024x1024.jpg?v=1653998912",
    category: "Drinks",
  },
  {
    id: 122,
    name: "Chikku Milkshake",
    description: "Sapota fruit blended with milk and a hint of cardamom.",
    price: 30,
    image: "https://vaya.in/recipes/wp-content/uploads/2017/11/Chikoo-Milkshake.jpg",
    category: "Drinks",
  },
  {
    id: 123,
    name: "Banana Milkshake",
    description: "Banana blended with milk and honey.",
    price: 27,
    image: "https://www.crazyvegankitchen.com/wp-content/uploads/2021/07/banana-milkshake4.jpeg",
    category: "Drinks",
  },
  {
    id: 124,
    name: "Dry Fruit Shake",
    description: "Assorted dry fruits blended with milk.",
    price: 35,
    image: "https://www.awesomecuisine.com/wp-content/uploads/2016/06/dry-fruits-milkshake.jpg",
    category: "Healthy",
  },
  {
    id: 125,
    name: "Dates Milkshake",
    description: "Dates and milk blended to a creamy shake.",
    price: 30,
    image: "https://yummynotes.net/wp-content/uploads/2019/05/dates-milkshake-recipe-5-585x585.jpg",
    category: "Drinks ",
  },

  // Healthy Foods (126-150)
  {
    id: 126,
    name: "Sprouts Salad",
    description: "Mixed sprouts, onions, tomatoes, tossed with lemon and spices.",
    price: 32,
    image: "https://www.funfoodfrolic.com/wp-content/uploads/2020/09/Sprout-Salad-Thumbnail-500x375.jpg",
    category: "Healthy",
  },
  {
    id: 127,
    name: "Mixed Fruit Raita",
    description: "Chopped fruits in lightly sweetened yogurt.",
    price: 28,
    image: "https://hindi.news24online.com/wp-content/uploads/2023/03/mixed-fruit-raita-recipe.jpg",
    category: "Healthy",
  },
  {
    id: 128,
    name: "Brown Rice Pongal",
    description: "Wholesome pongal made with brown rice and moong dal.",
    price: 38,
    image: "https://www.saffrontrail.com/wp-content/uploads/2016/01/chakkara-pongal-with-brown-rice-recipe.1024x1024.jpg",
    category: "Healthy",
  },
  {
    id: 129,
    name: "Oats Upma",
    description: "Healthy upma made with oats and vegetables.",
    price: 36,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2014/08/oats-upma.jpg",
    category: "Healthy",
  },
  {
    id: 130,
    name: "Quinoa Dosa",
    description: "Crispy dosas made with quinoa and rice.",
    price: 40,
    image: "https://www.cookingcarnival.com/wp-content/uploads/2015/01/Quinoa-Dosa-recipe-500x375.jpg",
    category: "Healthy",
  },
  {
    id: 131,
    name: "Vegetable Stew",
    description: "Kerala style mixed vegetable stew in coconut milk.",
    price: 44,
    image: "https://foodsharingvegan.com/wp-content/uploads/2022/06/Vegetable-Stew-Plant-Based-on-a-Budget-1-2.jpg",
    category: "Lunch, Healthy",
  },
  {
    id: 132,
    name: "Millet Pongal",
    description: "Mixed millet and dal pongal, rich in fiber.",
    price: 38,
    image: "https://everydaynourishingfoods.com/wp-content/uploads/2020/10/millet-pongal-breakfast-recipe.jpg",
    category: "Breakfast, Healthy",
  },
  {
    id: 133,
    name: "Moong Dal Chilla",
    description: "Savory pancakes made with ground moong dal.",
    price: 32,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/07/moong-dal-chilla.jpg",
    category: "Breakfast, Healthy",
  },
  {
    id: 134,
    name: "Kambu Koozh",
    description: "Pearl millet porridge, classic Tamil summer special.",
    price: 28,
    image: "https://premasculinary.com/wp-content/uploads/2015/03/Kambu-252520Koozh_thumb-25255B3-25255D.jpg",
    category: "Lunch, Healthy",
  },
  {
    id: 135,
    name: "Vegetable Salad",
    description: "Seasonal vegetables tossed with lemon and herbs.",
    price: 25,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/04/vegetable-salad-recipe.jpg",
    category: "Snacks, Healthy",
  },
  {
    id: 136,
    name: "Cabbage Poriyal",
    description: "Lightly stir-fried cabbage with coconut.",
    price: 22,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/cabbage-poriyal-recipe.jpg",
    category: "Lunch, Healthy",
  },
  {
    id: 137,
    name: "Beetroot Thoran",
    description: "Beetroot stir-fried with coconut and curry leaves.",
    price: 24,
    image: "https://www.kannammacooks.com/wp-content/uploads/2014/11/Beetroot-poriyal-with-coconut-thoran-stir-fry-vegetable-vegan-south-indian-225x225.jpg",
    category: "Lunch, Healthy",
  },
  {
    id: 138,
    name: "Carrot Beans Poriyal",
    description: "Lightly sautéed carrots and beans with coconut.",
    price: 24,
    image: "https://www.kannammacooks.com/wp-content/uploads/opos-carrot-beans-poriyal-stirfry.jpg",
    category: "Lunch, Healthy",
  },
  {
    id: 139,
    name: "Kollu Sundal",
    description: "Horse gram salad with coconut and spices.",
    price: 26,
    image: "https://www.sharmispassions.com/wp-content/uploads/2017/09/KolluSundal1-475x500.jpg",
    category: "Snacks, Healthy",
  },
  {
    id: 140,
    name: "Palak Dal",
    description: "Lentils cooked with spinach and spices.",
    price: 34,
    image: "https://www.fatrainbow.com/wp-content/uploads/2021/09/instant-pot-dal-palak.jpg",
    category: "Lunch, Healthy",
  },
  {
    id: 141,
    name: "Bottle Gourd Kootu",
    description: "Bottle gourd cooked with dal and coconut.",
    price: 30,
    image: "https://i.ytimg.com/vi/oYQY2wFY9-U/maxresdefault.jpg",
    category: "Lunch, Healthy",
  },
  {
    id: 142,
    name: "Pumpkin Curry",
    description: "Mild pumpkin curry with coconut and spices.",
    price: 28,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/10/pumpkin-curry-recipe.jpg",
    category: "Lunch, Healthy",
  },
  {
    id: 143,
    name: "Green Gram Sundal",
    description: "Steamed whole green gram with coconut.",
    price: 26,
    image: "https://www.awesomecuisine.com/wp-content/uploads/2013/09/green_gram_sweet_sundal-500x470.jpg",
    category: "Snacks, Healthy",
  },
  {
    id: 144,
    name: "Aval Upma",
    description: "Beaten rice cooked with mild spices and vegetables.",
    price: 22,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2024/04/aval-upma-poha-upma-recipe.jpg",
    category: "Breakfast, Healthy",
  },
  {
    id: 145,
    name: "Oats Dosa",
    description: "Thin crispy dosa made with oats and rice flour.",
    price: 32,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/instant-oats-dosa-recipe.jpg",
    category: "Breakfast, Healthy",
  },
  {
    id: 146,
    name: "Ragi Roti",
    description: "Finger millet flatbreads with onions and green chilies.",
    price: 28,
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2024/04/ragi-roti-nachni-roti-recipe.jpg",
    category: "Breakfast, Healthy",
  },
  {
    id: 147,
    name: "Vegetable Soup",
    description: "Mixed vegetable soup with ginger and pepper.",
    price: 25,
    image: "https://static01.nyt.com/images/2023/10/12/multimedia/LH-vegetable-soup-ckfp-copy/LH-vegetable-soup-ckfp-mediumSquareAt3X.jpg",
    category: "Snacks, Healthy",
  },
  {
    id: 148,
    name: "Broccoli Stir Fry",
    description: "Broccoli sautéed with garlic and mild spices.",
    price: 34,
    image: "https://www.southernliving.com/thmb/wSoW1RBRcqliXC4f8vc9UZNUZR8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/2612101_QFSGr_Skillet_Beef_Broccoli_259-7c55762848914163ba7af09e1e2ac862.jpg",
    category: "Lunch, Healthy",
  },
  {
    id: 149,
    name: "Mixed Millet Khichdi",
    description: "Assorted millets cooked with dal and vegetables.",
    price: 38,
    image: "https://www.kaulige.com/wp-content/uploads/2017/10/Multi-Millet-Khichdi.jpg",
    category: "Lunch, Healthy",
  },
  {
    id: 150,
    name: "Fruit Salad",
    description: "Fresh seasonal fruits, chopped and tossed.",
    price: 30,
    image: "https://www.cubesnjuliennes.com/wp-content/uploads/2022/06/Fresh-Summer-Fruit-Salad-Recipe.jpg",
    category: "Snacks, Healthy",
  },
];


